spring.application.name=task_manager
spring.datasource.url=jdbc:mysql://localhost:3306/mydb
spring.datasource.username=root
spring.datasource.password=Waw.com1

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/taskmanager
